### ISSUE TITLE
Natalie's Deduper Pseudocode Peer Review 

### ISSUE THREAD

**Issue by Natalie-Winans** [kate-roth/Deduper#2]
**Does the proposed algorithm make sense to you? Can you follow the logic?**
Yes, the proposed algorithm makes sense and is clearly written, making it easy to follow the logic.

**Does the algorithm do everything it's supposed to do?** 
Yes, it appears to everything it’s supposed to do with the exception perhaps of storing duplicated reads in a separate outfile. This is an easy fix. Overall, looks like a really good foundation for writing the actual code.

**Are proposed functions reasonable? Are they "standalone" pieces of code?**
The code isn’t broken down into functions, which makes sense when thinking about using functions as a way to reduce repetition in the code (which is how I use them too). However, I have read arguments that functions can be used to improve code readability and reduce complexity of the main code. In this case, since your main code doesn’t repeat itself, I don’t think functions are strictly necessary.

**Additional Comments/Questions:**
- Line 9: Will you run samtools sort first before executing your code, or can you incorporate this step into your script?
- Line 48: I believe Leslie said we should keep track of the duplicate reads. I see that you are counting them, but you might also consider writing them out to a “duplicates” outfile.
- Line 54: Should the SAM header lines be written to the outfiles as well? 
- Line 67: I like that you’re checking to see if the read is mapped, I didn’t even think of that. If the read is not mapped, it looks like you’re skipping the line, as written. I imagine you’ll want to write it out either to the unknown file or a separate unmapped outfile?
- Line 74: I’m still a little confused about this part. This is the same way I was planning to deal with soft-clipping in the reads mapped to the reverse strand, but one of my reviewers brought up some points that are making me rethink this strategy.
- Lines 79+: I like the way you use the temp dictionary to check for duplicates! Cool idea.

**Comment by kate-roth** [comment]
thank you for the feedback Natalie!
