### ISSUE TITLE
Nikki's Pseudocode Peer Review

### ISSUE THREAD

**Issue by nikkiszc** [kate-roth/Deduper#3]
•	Does the proposed algorithm make sense to you? Can you follow the logic?
Your code was very logical, the progression made sense and the indentation made it very easy to read and follow. I also liked that you included counters for the number of unknown UMIs, duplicates and non-duplicates. I also saw that sets are more efficiently looked through than lists, so thumbs up from me!

•	Does the algorithm do everything it's supposed to do? 
So I’m definitely not sure about this, but I was talking to Pete and he made it sound like for reverse strands, in order to determine where the “start” of the read is (on the left side), the true adjusted position should take into account all the numbers in the CIGAR string, besides any soft clipping at the front. Once again, ask Pete- I’m not sure. Maybe I’m completely wrong…

•	Are proposed functions reasonable? Are they "standalone" pieces of code?
It’s possible that you might want to break up your large code into smaller functions for each of the four pertinent pieces of information (but maybe you were already planning on doing that). Using a dictionary of UMI:tuple is an interesting idea, I like it! Sounds like it will be very efficient combined with current_refname.

**Comment by kate-roth** [comment]
thank you for the feedback Nikki!
